"""empty message

Revision ID: 86bb4bb06f90
Revises: 13ad0677b64d
Create Date: 2025-01-07 16:05:26.995159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bb4bb06f90'
down_revision = '13ad0677b64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_Vehicles_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('Vehicles_id')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Vehicles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key('favorites_Vehicles_id_fkey', 'vehicles', ['Vehicles_id'], ['id'])
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
